## 임베딩 Embedding
자연어를 숫자나 벡터 형태로 변환할 필요가 있다.<br>
단어나 문장을 수치화해 벡터 공간으로 표현하는 과정이다.<br>

종류에는 단어 임베딩과 문장 임베딩이 있다.<br>

### 단어 임베딩 - 원-핫 인코딩
단어를 숫자 벡터로 변환하는 가장 기본적인 방법이다. <br>
단 하나의 값만 1이고 나머지 요솟값은 0인 인코딩이다.<br>
결과를 원-핫 벡터라고 한다.<br>

In [4]:
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = "오늘 날씨는 구름이 많아요."

# 리스트형태로 명사를 추출 
nouns = komoran.nouns(text)
print(nouns) 


# 딕셔너리형태로 단어 사전 구축 및 단어별 인덱스 부여, 중복 제외
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

# 원-핫 인코딩
nb_classes = len(dics) # 원-핫 벡터 크기 결정
targets = list(dics.values()) # 단어들을 리스트로 변환
one_hot_targets = np.eye(nb_classes)[targets] # 단위행렬 반환
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
